version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web/tk/joberchip-fe-refactoring
    overwrite: yes
permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu
